In [1]:
import sklearn
print(sklearn.__version__)

1.6.1


In [3]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier # 결정트리 기반 분류 모델
from sklearn.model_selection import train_test_split

In [7]:
import pandas as pd

iris = load_iris()
iris_data = iris.data # iris.data는 데이터셋에서 피쳐만으로 구성된 데이터를 numpy로 가지고있음
iris_label = iris.target
iris_target_name = iris.target_names
print(len(iris_data))
print(iris_data[:5])
print(iris_label)
print(iris_target_name)

150
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
['setosa' 'versicolor' 'virginica']


In [9]:
iris_df = pd.DataFrame(data=iris_data, columns=iris_target_name)
iris_df['label'] = iris.target
iris_df.head(5)

ValueError: Shape of passed values is (150, 4), indices imply (150, 3)